# Generated by Django 3.0.3 on 2020-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_candidate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='family_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
