# Generated by Django 3.0.3 on 2020-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200218_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='choice',
            field=models.CharField(choices=[('PEDIATRIC', 'Pediatric'), ('GENERALIST', 'Generalist'), ('OPHTALMOLOGY', 'Ophtalmology'), ('SURGERY', 'Surgery'), ('CARDIOLOGY', 'Cardiology')], max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(choices=[('ALBA IULIA', 'Alba Iulia'), ('CLUJ-NAPOCA', 'Cluj-Napoca'), ('BUCHAREST', 'Bucharest'), ('SURGERY', 'Surgery'), ('CARDIOLOGY', 'Cardiology')], max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='year',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)]),
        ),
    ]
