# Generated by Django 3.0.3 on 2020-03-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200313_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='about',
            field=models.TextField(max_length=2550),
        ),
    ]
