# Generated by Django 3.0.3 on 2020-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200313_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
