# Generated by Django 3.0.3 on 2020-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_hospital_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
