# Generated by Django 3.0.3 on 2020-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='city',
        ),
    ]
