# Generated by Django 3.0.3 on 2020-04-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_hospital_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Specialty'),
        ),
    ]
