# Generated by Django 3.0.3 on 2020-04-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200422_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='hospital',
        ),
        migrations.AddField(
            model_name='favorite',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Service'),
            preserve_default=False,
        ),
    ]
