# Generated by Django 3.0.3 on 2020-04-22 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0017_auto_20200422_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paperwork_Service_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Paperwork_Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
